export interface APIResponse {
  oficial: Blue;
  blue: Blue;
  oficial_euro: Blue;
  blue_euro: Blue;
  last_update: string;
}

export interface Blue {
  value_avg: number;
  value_sell: number;
  value_buy: number;
}

export const getDollarPrice = async () => {
  const response = await fetch("https://api.bluelytics.com.ar/v2/latest");

  if (!response.ok) {
    return null;
  }
  const data = (await response.json()) as APIResponse;

  const { blue } = data;

  return blue.value_avg;
};
// Generated by https://quicktype.io
